### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Soyal7** [cnr-isti-vclab/piccante#13]
When reading .exr files only half of the allocated memory gets freed. I tested with tinyexr.

![img1](https://i.imgur.com/lynCcE7.jpg)
## 2-Before destruction
![img2](https://i.imgur.com/mNDERjN.jpg)
## 3-After destruction
![img3](https://imgur.com/BGMiAFP.jpg)
```c++
#include <iostream>
#define _CRT_SECURE_NO_DEPRECATE
#define _CRT_NONSTDC_NO_DEPRECATE
#define _CRT_SECURE_NO_WARNINGS
#define PIC_ENABLE_INLINING
#define PIC_DISABLE_OPENGL
#include <piccante.hpp>

void loadHDR(const std::string &filePath)
{
	auto image = pic::Image{ filePath };
	std::cout << "Image loaded" << std::endl;
}

int main()
{
	loadHDR("F:/Graphics/HDR/Manhattan Nights Vol. 1/5TH_AVENUE.exr");

	std::cout << "Press Enter to continue...";
	std::cin.get();
}
```

**Comment by banterle** [comment]
I made some changes, can you check if it work now, please?

**Comment by Soyal7** [comment]
These changes seem to introduce some problems with the headers:
```
include\algorithms\color_classification.hpp(56,5): error C2065:  'FilterWhiteBalance': undeclared identifier
include\algorithms\color_classification.hpp(56,24): error C2146:  syntax error: missing ';' before identifier 'flt_wb'
include\algorithms\color_classification.hpp(56,24): error C2065:  'flt_wb': undeclared identifier
include\algorithms\color_classification.hpp(57,5): error C2065:  'flt_wb': undeclared identifier
include\algorithms\color_classification.hpp(63,17): error C3861:  'applyWhiteBalance': identifier not found
include\JNI\find_checker_board.hpp(111,22): error C3861:  'applyWhiteBalance': identifier not found
include\JNI\find_checker_board.hpp(113,22): error C3861:  'applyWhiteBalance': identifier not found
```

**Comment by banterle** [comment]
I fixed these issues, please check, it should work now!

**Comment by Soyal7** [comment]
Now it compiles, but unfortunately, the same problem persists. I also noticed that tiled .exrs are not being loaded at all, unlike scanlined ones.

**Comment by banterle** [comment]
> I also noticed that tiled .exrs are not being loaded at all, unlike scanlined ones.

For those cases, you need to disable TinyEXR and to enable OpenEXR.
To do that you need to add these two lines of code before including piccane.hpp:
#define PIC_DISABLE_TINY_EXR
#define PIC_ENABLE_OPEN_EXR

Note that, after doing this, you need to download OpenEXR library and install it on your machine.

**Comment by banterle** [comment]
I added memory release with TinyEXR's functions. It should work now.

**Comment by Soyal7** [comment]
Now it works correctly. Thanks!

**Comment by banterle** [comment]
you are welcome!
